### ISSUE TITLE
A question of dynamic groups

### ISSUE THREAD

**Issue by lucky1024** [binance-chain/tss-lib#121]
Using the feature `Dynamic Groups`, can I change an old threshold configuration to any other threshold configuration while keeping the secret ? For example, change (3, 5) to (6, 7).

I don't find `Dynamic Groups` in paper GG18.  The implementation of dynamic groups comes from which paper?

**Comment by omershlo** [comment]
Hi @lucky1024 , 
yes, Dynamic groups allows for old committee to assign a new committee with a new secret shares. The old committee should delete their keys but in case they are backed up I assume you can have both committees at the same time. 

The protocol is indeed not part of GG18, however, it is a simple enough protocol that uses common cryptographic building blocks. I would make sure you are at peace with the security of the protocol (perhaps proving it yourself) before using it. 
If you indeed decide to prove the protocol (or even write it as a spec) that would be a great contribution!

**Comment by lucky1024** [comment]
I‘m not familiar with these **simple enough protocol** 😭

I find there are many papers focus this topic:
[SLL08] David A. Schultz, Barbara Liskov, and Moses D. Liskov. Mobile proactive secret sharing. 2008.
[BDLO15] Joshua Baron, Karim El Defrawy, Joshua Lampkins, and Rafail Ostrovsky. Communication-optimal proactive secret sharing for dynamic groups. 2015.
[MZW+19] Sai Krishna Deepak Maram, Fan Zhang, Lun Wang, Andrew Low, Yupeng Zhang, Ari Juels, and Dawn Song. CHURP: dynamic-committee proactive secret sharing. 2019

Could you give me some clues about implementation detail in tss-lib?

**Comment by omershlo** [comment]
Here is the analysis taken from https://eprint.iacr.org/2020/1052.pdf : 
![Screen Shot 2020-12-03 at 11 21 29](https://user-images.githubusercontent.com/2446179/100989621-b5990d00-3559-11eb-8496-ffc5a1bb3a5c.png)
there is now an extra round at the end to verify all parties got correct messages and otherwise abort.
The protocol resembles a distributed key generation but instead of generating fresh random shares the parties secret share the existing shares and check that the public key remains the same.
 Remember that the paper assumes that the protocol implementation is secure. I never tried to write down the security guarantees or prove security claims about this protocol. I suggest you do your own research

**Comment by lucky1024** [comment]
Thank you for sharing such useful information.
